# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingdata',
            options={'ordering': ('created_at',)},
        ),
    ]
