# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0004_auto_20171002_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingdata',
            name='duokd',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ratingdata',
            name='solokd',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ratingdata',
            name='squadkd',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
