# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0005_auto_20171019_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingdata',
            name='duofppkd',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ratingdata',
            name='solofppkd',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ratingdata',
            name='squadfppkd',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
