# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0006_auto_20171022_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingdata',
            name='season',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
