# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0007_ratingdata_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingdata',
            name='ranking',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
