# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0008_ratingdata_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingdata',
            old_name='ranking',
            new_name='duoRanking',
        ),
        migrations.AddField(
            model_name='ratingdata',
            name='duofppRanking',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ratingdata',
            name='soloRanking',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ratingdata',
            name='solofppRanking',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ratingdata',
            name='squadRanking',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ratingdata',
            name='squadfppRanking',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
